### PR TITLE
Add stations list by country code and advanced search

### PR DESCRIPTION
**Pull request by SekyCz**

### CODE REVIEW

**Comment by sfuhrm** [comment]
Hey @SekyCz 

thanks for your PR! I have to admit that it's very difficult to see what changed since some mechanism (IDE auto-reformat on save?) reformatted the whole file. Can you file a PR without these automatic formattings? This would be great.

Stephan

**Comment by SekyCz** [comment]
Hi @sfuhrm, 
Thanks for fast response! I've returned formatting to previous one, however some parts still seems to be detected by my IDE as unchanged (even though it did some formatting). However It should be more readable now. If not then I'll adjust the rest manually.

**Comment by sfuhrm** [comment]
@SekyCz , yes, your IDE is hiding away formatting changes. It's probably better to patch your changes to a vanilla checkout with a text editor.  This way your IDE won't change the formatting.

Taking a look at the content:
* A unit test would be great. I'd really love to trace a bit into the code, request/responses and see what it does. Here is the switch between recording HTTP calls and saving them to disk (true) and just using previously recorded HTTP responses (false): https://github.com/sfuhrm/radiobrowser4j/blob/d2e1c0a8e3f59a05980ba9638ee686f6c389344d/radiobrowser4j/src/test/java/de/sfuhrm/radiobrowser4j/RadioBrowserTest.java#L72
Maybe it helps?
* `SearchKey` seems to only have parts of the possibilities of the API. May be add the remaining keys?
* I think using a standard JDK approach with type `Map<SearchKey,String>` instead of a custom class `SearchParameter` as a vararg parameter is a simpler solution with less custom code and more support in JDKs classes. Can you rewrite that?
* The isolated SearchMode parameter without the searchterm seems to be a misunderstanding. In the existing code we have the combination "SearchMode + searchTerm" all over the place. SearchMode without searchTerm is a bit difficult to understand, 
What API endpoint are you addressing? This one? https://de1.api.radio-browser.info/#Advanced_station_search - then the URL would need to be.../json/stations/search, not include the SearchMode in the path?

See here for the method discussed:

```
+    public Stream<Station> listStationsBy(
+            @NonNull final SearchMode searchMode,
+            final SearchParameter... searchParam) {
```


Probably the best next step is to start with the unit test mentioned above.

Hope my points are understandable. Don't hesitate to ask :). When the IDE reformatting is gone we can use the standard Github code review stuff.

Looking forward seeing more code from you!

**Comment by SekyCz** [comment]
Hi @sfuhrm,
Thanks for all the points. I need to address some more adjustments.
I'll close this pull request now and get to it later.

**Pull request closed without merging**
