### PR TITLE
Update URLs to "MDS" stream

### PR DESCRIPTION
**Pull request by romik-g**
Stream "Модель для Сборки" on stream.kazancity.net:8000/27-mds is a retransmission [1,2] of mds-station.com:8000/mds. Patch changes stream URL to original stream, as the copy of the stream on kazancity.net is planned to be shut off [2].

[1] https://mds-station.com/stats.xhtml - statistics page
[2] https://mds-station.com/news.xhtml - news page, see news dated 25.03.2019.

### CODE REVIEW

**Comment by sfuhrm** [comment]
Thank you for your PR!

**Comment by romik-g** [comment]
As edits are disabled on a web site, could we have DB updated, please? Thank you! [Link to the station](http://www.radio-browser.info/gui/#!/bytag/%D0%9C%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%B4%D0%BB%D1%8F%20%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8).

**Comment by sfuhrm** [comment]
@romik-g would love that, but this project is just a Java wrapper around the server.
The server is provided by @segler-alex
See this discussion to understand why he [disabled editing](https://github.com/segler-alex/radiobrowser-api/issues/39).

**Comment by romik-g** [comment]
Thank you, @sfuhrm!

**Pull request merged**
